### PR TITLE
Update to 2023.1.30

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@jan-janssen, does it make sense to keep building from source from GitHub for now with a note to switch to PyPI for the next release (assuming issues are fixed)?  That seems easier than patching the PyPI source, which is the only real alternative I can come up with.

**Comment by jan-janssen** [comment]
> @jan-janssen, does it make sense to keep building from source from GitHub for now with a note to switch to PyPI for the next release (assuming issues are fixed)? That seems easier than patching the PyPI source, which is the only real alternative I can come up with.

The issue is there are no tags on the Github repository.

**Comment by xylar** [comment]
Ah, I see.  That's not great!

**Comment by xylar** [comment]
Then, maybe if you can figure out what commit hash the 2023.1.23 PyPI release corresponds to, a patch to add `resources.txt` is the best option.

@ZhuozhaoLi and @yadudoc, I believe you may be involved in parsl development?  If so, are you in a position to push for having releases properly tagged in the future?

**Comment by jan-janssen** [comment]
A new version is released next Monday, then I can try it again.

**Comment by jan-janssen** [comment]
@xylar It is fixed now and ready to be merged.

**Comment by xylar** [comment]
@jan-janssen, thanks so much!  I'm reordering the requirement to match what I get from grayskull, just for my future convenience in maintaining the package.

**Comment by yadudoc** [comment]
@xylar We switched to an weekly automated release model with calver and the tagging is broken at the moment. I see how that is messing up packaging. It's on my plate to fix. Thank you all for pushing this :)

**Comment by xylar** [comment]
@yadudoc, no worries, we got it sorted but tagging would be really helpful because it makes verifying that the dependencies are correct a lot easier.

**Review by yadudoc — APPROVED** [review]
Changes look reasonable to me.

**Pull request merged**
